springBootVersion: "3.5.6"
jdbcDrivers:
  mysql:
    groupId: "com.mysql"
    artifactId: "mysql-connector-j"
    version: "9.7.0"
  mariadb:
    groupId: "org.mariadb.jdbc"
    artifactId: "mariadb-java-client"
    version: "3.1.4"
  oracle:
    groupId: "com.oracle.database.jdbc"
    artifactId: "ojdbc11"
    version: "23.26.1.0.0"
  mssql:
    groupId: "com.microsoft.sqlserver"
    artifactId: "mssql-jdbc"
    version: "12.6.1.jre11"
  postgresql:
    groupId: "org.postgresql"
    artifactId: "postgresql"
    version: "42.7.5"
  db2:
    groupId: "com.ibm.db2"
    artifactId: "jcc"
    version: "12.1.2.0"
